name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint: 
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: lint
        run: go get -u honnef.co/go/tools/cmd/staticcheck@latest &&
             $HOME/go/bin/staticcheck

  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: test
        run: go generate &&
             make
